# Generated by Django 6.0.6 on 2026-07-09 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WIN", "Win"),
                            ("LOSS", "Loss"),
                            ("PROCESS", "In progress"),
                            ("PLACEMENT", "Placement"),
                        ],
                        default="PLACEMENT",
                        max_length=20,
                    ),
                ),
                (
                    "winner",
                    models.CharField(
                        blank=True,
                        choices=[("BOT", "Computer"), ("PLAYER", "Player")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "winner",
                    models.CharField(
                        choices=[("BOT", "Computer"), ("PLAYER", "Player")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WIN", "Win"),
                            ("LOSS", "Loss"),
                            ("PROCESS", "In progress"),
                            ("PLACEMENT", "Placement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="game.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        choices=[("BOT", "Computer"), ("PLAYER", "Player")],
                        max_length=10,
                    ),
                ),
                ("length", models.PositiveSmallIntegerField()),
                ("start_x", models.PositiveSmallIntegerField()),
                ("start_y", models.PositiveSmallIntegerField()),
                (
                    "orientation",
                    models.CharField(
                        choices=[("H", "Horizontal"), ("V", "Vertical")],
                        max_length=1,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ships",
                        to="game.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        choices=[("BOT", "Computer"), ("PLAYER", "Player")],
                        max_length=10,
                    ),
                ),
                ("x", models.PositiveSmallIntegerField()),
                ("y", models.PositiveSmallIntegerField()),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("MISS", "Miss"),
                            ("HIT", "Hit"),
                            ("SUNK", "Ship destroyed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="game.game",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("game", "owner", "x", "y"),
                        name="unique_move_per_target_cell",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Cell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        choices=[("BOT", "Computer"), ("PLAYER", "Player")],
                        max_length=10,
                    ),
                ),
                ("x", models.PositiveSmallIntegerField()),
                ("y", models.PositiveSmallIntegerField()),
                ("has_ship", models.BooleanField(default=False)),
                ("is_hit", models.BooleanField(default=False)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        to="game.game",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cells",
                        to="game.ship",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("game", "owner", "x", "y"), name="unique_cell_per_board"
                    )
                ],
            },
        ),
    ]
